### ISSUE TITLE
Ggplot error in trying to make basic graph

### ISSUE THREAD

**Issue by shahchintal** [duttashi/visualizer#76]
elonmusk_tweets <- read_excel("elonmusk_tweets.xlsx")

count2015 <- elonmusk_tweets %>%
  count(Year) %>%
  filter(Year == "2015") %>%
  select(n)

ggplot(elonmusk_tweets, aes(x=Year, y=count2015, col=origin))+
  geom_bar()
error:Don't know how to automatically pick scale for object of type tbl_df/tbl/data.frame. Defaulting to continuous. Error in is.finite(x) : default method not implemented for type 'list'

I am just trying to create a graph that shows years 2015 on the x axis and the count per year on the y axis and have no idea what i am doing wrong

**Comment by duttashi** [comment]
@shahchintal did you care to read the `README` [file](https://github.com/duttashi/visualizer/blob/master/README.md) of this repository?

I've written it explicitly in README that if you've a Q, then ask it on SO. Moreover, your Q is not reproducible. Read this [post](https://stackoverflow.com/help/how-to-ask) on SO and learn how to ask a Q. Closing the issue as it's off topic.

**Comment by shahchintal** [comment]
I am new to coding and GitHub. My apologies, I thought I was asking a similar question. However, your response was rude, and not in spirit of a collaborative environment. I hope you don't speak to people this way in person.

**Comment by duttashi** [comment]
@shahchintal the response was appropriate. If you perceive it as rude or offensive it's unfortunate. Moreover, the _collaborative environment_ that you refer too, does not apply to repository such as this one in question. This repository does not serve as a "collaborative interface" or application programming interface in short!
